#%RAML 1.0
title: Moyashi

/boards:
  post:
    body:
      application/json:
        type: object
        properties:
          name:
            required: true
            type: string
          slug:
            required: true
            type: string
    responses:
      201:
        body:
          application/json:
            type: object
            properties:
              name: string
              slug: string
              created_at: string
  /{board}:
    /threads:
      /{id}:

/admin:
  /users:
    /{id}:

/posters:
  /{id}:
    /ban:
